version: '3.8'
services:
  gateway:
    build: ./apps/gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "2222:2222"
    networks:
      - some-network
  auth:
    build: ./apps/auth
    restart: always
    hostname: auth
    env_file:
      - .env
    networks:
      - some-network
  plan:
    build: ./apps/plans
    restart: always
    hostname: plan
    env_file:
      - .env
    networks:
      - some-network
  clinic:
    build: ./apps/clinics
    restart: always
    hostname: clinic
    env_file:
      - .env
    networks:
      - some-network
  chat:
    build: ./apps/chats
    restart: always
    hostname: chat
    env_file:
      - .env
    networks:
      - some-network
    
  mailer:
    build: ./apps/mailer
    restart: always
    hostname: mailer
    env_file:
      - .env
    networks:
      - some-network
  noti:
    build: ./apps/notification
    restart: always
    hostname: notification
    env_file:
      - .env
    networks:
      - some-network
  staff:
    build: ./apps/staffs
    restart: always
    hostname: staff
    env_file:
      - .env
    networks:
      - some-network
  payment:
    build: ./apps/payment
    restart: always
    hostname: payment
    env_file:
      - .env
    networks:
      - some-network
networks:
  some-network:
    driver: bridge