export enum ClinicCommand {
  CLINIC_CREATE = 'CLINIC_CREATE',
  CLINIC_LIST = 'CLINIC_LIST',
  UPDATE_CLINIC = 'UPDATE_CLINIC',
  ADD_USER_TO_CLINIC = 'ADD_USER_TO_CLINIC',
  SUBSCRIBE_PLAN = 'SUBSCRIBE_PLAN',
  GET_USERS_BY_CLINIC = 'GET_USERS_BY_CLINIC',
  UPDATE_SUBSCRIBE_PLAN = 'UPDATE_SUBSCRIBE_PLAN',
  GET_PERMISSIONS = 'GET_PERMISSIONS',
}
