export enum MedicalSupplierCommand {
  MEDICAL_SUPPLIER_CREATE = 'MEDICAL_SUPPLIER_CREATE',
  MEDICAL_SUPPLIER_LIST = 'MEDICAL_SUPPLIER_LIST',
  MEDICAL_SUPPLIER_UPDATE = 'MEDICAL_SUPPLIER_UPDATE',
  MEDICAL_SUPPLIER_DELETE = 'MEDICAL_SUPPLIER_DELETE',
  MEDICAL_SUPPLIER_GET = 'MEDICAL_SUPPLIER_GET',
}
