export enum PatientReceptionCommand {
  CREATE_PATIENT_RECEPTION = 'CREATE_PATIENT_RECEPTION',
  CREATE_PATIENT_RECEPTION_2 = 'CREATE_PATIENT_RECEPTION_2',
  UPDATE_PATIENT_RECEPTION = 'UPDATE_PATIENT_RECEPTION',
  GET_MEDICAL_RECORD = 'GET_MEDICAL_RECORD',
  GET_LIST_MEDICAL_RECORD = 'GET_LIST_MEDICAL_RECORD',
  UPDATE_MEDICAL_RECORD_SERVICE = 'UPDATE_MEDICAL_RECORD_SERVICE',
  REQUEST_SERVICE = 'REQUEST_SERVICE',
  GET_REQUEST_SERVICE_BY_CODE = 'GET_REQUEST_SERVICE_BY_CODE',
  UPDATE_MEDICAL_RECORD_PRESCRIPTION = 'UPDATE_MEDICAL_RECORD_PRESCRIPTION',
}
