export enum AuthCommand {
  USER_CREATE = 'user_create',
  USER_LOGIN = 'user_login',
  USER_VERIFY = 'user_verify',
  USER_CONFIRM = 'user_confirm',
  USER_OAUTH_LOGIN = 'user_oauth_login',
  USER_GET_ACCOUNTS = 'user_get_accounts',
  USER_DELETE_ACCOUNT = 'user_delete_account',
  USER_GET = 'user_get',
  USER_FIND_ACCOUNT = 'user_find_account',
  USER_CHECK_VERIFY = 'user_check_verify',
  LINK_ACCOUNT_WITH_EMAIL = 'link_account_with_email',
  CHANGE_PASSWORD = 'change_password',
  RESET_PASSWORD = 'reset_password',
  RESET_PASSWORD_VERIFY = 'reset_password_verify',
  ADD_NEW_PASSWORD = 'add_new_password',
  FIND_USER_BY_EMAIL = 'find_user_by_email',
  FIND_SCHEDULE_BY_ID = 'find_schedule_by_id',
  FIND_SCHEDULE_BY_USER_ID = 'find_schedule_by_user_id',
  UPDATE_USER = 'update_user',
  FIND_ALL_USER_BY_EMAIL = 'find_all_user_by_email',
}
