export enum PlanCommand {
  PLAN_CREATE = 'PLAN_CREATE',
  CREATE_OPTION = 'CREATE_OPTION',
  PLAN_UPDATE = 'PLAN_UPDATE',
  GET_ALL_ACTIVE_OPTION = 'GET_ALL_ACTIVE_OPTION',
  GET_PLAN_BY_ID = 'GET_PLAN_BY_ID',
  GET_ALL_PLAN = 'GET_ALL_PLAN'
}
