export enum ScheduleCommand {
    FIND_SCHEDULE_BY_ID = 'FIND_SCHEDULE_BY_ID',
    FIND_SCHEDULE_BY_USER_ID = 'FIND_SCHEDULE_BY_USER_ID',
    CREATE_SCHEDULE = 'CREATE_SCHEDULE',
    DELETE_SCHEDULE = 'DELETE_SCHEDULE',
    UPDATE_SCHEDULE = 'UPDATE_SCHEDULE',
}