export enum ClinicCommand {
  CLINIC_CREATE = 'CLINIC_CREATE',
  CLINIC_LIST = 'CLINIC_LIST',
  UPDATE_CLINIC = 'UPDATE_CLINIC',
  ADD_USER_TO_CLINIC = 'ADD_USER_TO_CLINIC',
  SUBSCRIBE_PLAN = 'SUBSCRIBE_PLAN',
  UPDATE_USER = 'update_user',
}
